### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by RyanJellesed** [fedosejev/react-essentials#77]
Ryans-MacBook-Pro:snapkite-engine ryanjellesed$ npm start

> snapkite-engine@0.1.2 start /Users/ryanjellesed/snapkite-engine
> node app.js

module.js:433
    throw err;
    ^

SyntaxError: /Users/ryanjellesed/snapkite-engine/config.json: Unexpected token

```
at Object.parse (native)
at Object.Module._extensions..json (module.js:430:27)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/Users/ryanjellesed/snapkite-engine/app.js:1:85)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
```

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ryanjellesed/snapkite-engine/npm-debug.log

**Comment by Kulakshi** [comment]
I'm also getting the same kind of an error once 'nmp start' is executed from the terminal. 

> snapkite-engine@0.1.2 start /home/kulakshi/Work/react/kulAppTest1/snapkite-engine
> node app.js

module.js:485
    throw err;
          ^
SyntaxError: /home/kulakshi/Work/react/kulAppTest1/snapkite-engine/config.json: Unexpected token :
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kulakshi/Work/react/kulAppTest1/snapkite-engine/app.js:1:85)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by goesbysteve** [comment]
I had it to. Try checking there are no leading or trailing spaces in the Twitter keys in the /snapkite-engine/config.json API node. If you cut and paste from the Twitter apps page you may have got extra characters.

Also you need to generate Twitter OAuth keys. Assuming you have already created the Twitter app as in the book Chpt 1 I found these steps worked for me -

Go to apps.twitter.com
Select the app you created
In the Callback URL enter http://127.0.0.1:3000
Now go to the Keys and Access Tokens tab
Scroll down and click on the Generate Access Keys button
The page will refresh, scroll back down and you'll now have the "accessTokenKey" & "accessTokenSecret" you'll need for the config.json.
npm start should now work, you'll see "Listening on port 3000"

This is because the Twitter API now requires OAUTH and the snapkite engine wants these keys to enable it to authenticate with Twitter. I haven't got as far in the book to know this actually succeeds in the React app using it.

I hope this helps you.

**Comment by theNewPyGuy** [comment]
Thank you stevegibbings, solved the problem for me.

**Comment by fedosejev** [comment]
Thanks for the support @stevegibbings.
